In [2]:
import pandas as pd
import matplotlib as plt
import seaborn as sns



In [4]:
#reading dataset
df1=pd.read_csv('../input/diabetes-dataset/diabetic_data.csv',keep_default_na=' ')

In [5]:
#no. of rows and columns
df1.shape

(101766, 50)

In [6]:
#column names
df1.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [7]:
df1.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

In [8]:
categorical=df1.select_dtypes(include=['object'])
numeric=df1.select_dtypes(exclude=['object'])

In [9]:
categorical['encounter_id']=df1['encounter_id']

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [10]:
#setting index
numeric.set_index(['encounter_id'])
#categorical.set_index(['encounter_id'])

patient_nbr  admission_type_id  discharge_disposition_id  \
encounter_id                                                             
2278392           8222157                  6                        25   
149190           55629189                  1                         1   
64410            86047875                  1                         1   
500364           82442376                  1                         1   
16680            42519267                  1                         1   
...                   ...                ...                       ...   
443847548       100162476                  1                         3   
443847782        74694222                  1                         4   
443854148        41088789                  1                         1   
443857166        31693671                  2                         3   
443867222       175429310                  1                         1   

              admission_source_id  time_in_hospital  num_lab_procedures  \
encounter_id                                                              
2278392                         1                 1                  41   
149190                          7                 3                  59   
64410                           7                 2                  11   
500364                          7                 2                  44   
16680                           7                 1                  51   
...                           ...               ...                 ...   
443847548                       7                 3                  51   
443847782                       5                 5                  33   
443854148                       7                 1                  53   
443857166                       7                10                  45   
443867222                       7                 6                  13   

              num_procedures  num_medications  number_outpatient  \
encounter_id                                                       
2278392                    0                1                  0   
149190                     0               18                  0   
64410                      5               13                  2   
500364                     1               16                  0   
16680                      0                8                  0   
...                      ...              ...                ...   
443847548                  0               16                  0   
443847782                  3               18                  0   
443854148                  0                9                  1   
443857166                  2               21                  0   
443867222                  3                3                  0   

              number_emergency  number_inpatient  number_diagnoses  
encounter_id                                                        
2278392                      0                 0                 1  
149190                       0                 0                 9  
64410                        0                 1                 6  
500364                       0                 0                 7  
16680                        0                 0                 5  
...                        ...               ...               ...  
443847548                    0                 0                 9  
443847782                    0                 1                 9  
443854148                    0                 0                13  
443857166                    0                 1                 9  
443867222                    0                 0                 9  

[101766 rows x 12 columns]

In [11]:
def drop_col(df):
        drop_col=['patient_nbr']
        for  x in df.columns:
            if x!='encounter_id' and x.endswith('_id'):
                drop_col.append(x)
                
        
        return df.drop(drop_col,axis=1)
    
    


In [12]:
numeric1=drop_col(numeric).copy()

In [13]:
#Mean
numeric1.apply(lambda x:x.mean(),axis=0)

encounter_id          1.652016e+08
time_in_hospital      4.395987e+00
num_lab_procedures    4.309564e+01
num_procedures        1.339730e+00
num_medications       1.602184e+01
number_outpatient     3.693572e-01
number_emergency      1.978362e-01
number_inpatient      6.355659e-01
number_diagnoses      7.422607e+00
dtype: float64

In [14]:
numeric2=numeric1.loc[:,numeric1.columns!='encounter_id']

In [15]:
numeric2.describe().transpose()

count       mean        std  min   25%   50%   75%  \
time_in_hospital    101766.0   4.395987   2.985108  1.0   2.0   4.0   6.0   
num_lab_procedures  101766.0  43.095641  19.674362  1.0  31.0  44.0  57.0   
num_procedures      101766.0   1.339730   1.705807  0.0   0.0   1.0   2.0   
num_medications     101766.0  16.021844   8.127566  1.0  10.0  15.0  20.0   
number_outpatient   101766.0   0.369357   1.267265  0.0   0.0   0.0   0.0   
number_emergency    101766.0   0.197836   0.930472  0.0   0.0   0.0   0.0   
number_inpatient    101766.0   0.635566   1.262863  0.0   0.0   0.0   1.0   
number_diagnoses    101766.0   7.422607   1.933600  1.0   6.0   8.0   9.0   

                      max  
time_in_hospital     14.0  
num_lab_procedures  132.0  
num_procedures        6.0  
num_medications      81.0  
number_outpatient    42.0  
number_emergency     76.0  
number_inpatient     21.0  
number_diagnoses     16.0

In [16]:
#Quartiles to find IQR and figure out ouliers
Q1=numeric2.apply(lambda x:x.quantile(0.25),axis=0)
Q3=numeric2.apply(lambda x:x.quantile(0.75),axis=0)
IQR=Q3-Q1

In [17]:
# to return outliers
def dcf(x):
    IQR=x.quantile(0.75)-x.quantile(0.25)
    b=x.quantile(0.25)-IQR
    c=x.quantile(0.75) +IQR
    outliers=[x.loc[x> c],x.loc[x< b]]
    return outliers

In [18]:
s=numeric2.apply(lambda x: dcf(x),axis=0)

In [19]:
#list of outliers
s

time_in_hospital      [[13, 12, 12, 11, 13, 11, 12, 14, 14, 11, 11, ...
num_lab_procedures    [[87, 96, 88, 90, 93, 103, 85, 90, 87, 95, 97,...
num_procedures        [[5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6,...
num_medications       [[31, 32, 33, 39, 32, 33, 33, 31, 31, 61, 40, ...
number_outpatient     [[2, 1, 1, 1, 1, 1, 5, 2, 7, 1, 1, 9, 1, 3, 1,...
number_emergency      [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,...
number_inpatient      [[3, 6, 3, 5, 5, 4, 3, 5, 3, 3, 6, 3, 3, 3, 3,...
number_diagnoses      [[16, 13, 15, 16, 16, 13, 13, 13, 16, 16, 13, ...
dtype: object

In [20]:
#Percentage of outliers
s.apply(lambda x: len(x[0])*100/len(df1))

time_in_hospital       5.458601
num_lab_procedures     1.181141
num_procedures         7.892616
num_medications        5.146120
number_outpatient     16.448519
number_emergency      11.185465
number_inpatient       6.926675
number_diagnoses       0.076646
dtype: float64

In [21]:
#Null Values in columns 
numeric2.apply(lambda x:x.loc[x.isnull()],axis=1)
#Null values in rows
numeric2.apply(lambda x:x.loc[x.isnull()],axis=0)

Empty DataFrame
Columns: [time_in_hospital, num_lab_procedures, num_procedures, num_medications, number_outpatient, number_emergency, number_inpatient, number_diagnoses]
Index: []

In [22]:
#correlation among numerical attributes
numeric2.corr()

time_in_hospital  num_lab_procedures  num_procedures  \
time_in_hospital            1.000000            0.318450        0.191472   
num_lab_procedures          0.318450            1.000000        0.058066   
num_procedures              0.191472            0.058066        1.000000   
num_medications             0.466135            0.268161        0.385767   
number_outpatient          -0.008916           -0.007602       -0.024819   
number_emergency           -0.009681           -0.002279       -0.038179   
number_inpatient            0.073623            0.039231       -0.066236   
number_diagnoses            0.220186            0.152773        0.073734   

                    num_medications  number_outpatient  number_emergency  \
time_in_hospital           0.466135          -0.008916         -0.009681   
num_lab_procedures         0.268161          -0.007602         -0.002279   
num_procedures             0.385767          -0.024819         -0.038179   
num_medications            1.000000           0.045197          0.013180   
number_outpatient          0.045197           1.000000          0.091459   
number_emergency           0.013180           0.091459          1.000000   
number_inpatient           0.064194           0.107338          0.266559   
number_diagnoses           0.261526           0.094152          0.055539   

                    number_inpatient  number_diagnoses  
time_in_hospital            0.073623          0.220186  
num_lab_procedures          0.039231          0.152773  
num_procedures             -0.066236          0.073734  
num_medications             0.064194          0.261526  
number_outpatient           0.107338          0.094152  
number_emergency            0.266559          0.055539  
number_inpatient            1.000000          0.104710  
number_diagnoses            0.104710          1.000000

In [23]:
import numpy as np
categorical.describe(include=[np.object]).transpose().iloc[:,:]



count unique        top    freq
race                      101766      6  Caucasian   76099
gender                    101766      3     Female   54708
age                       101766     10    [70-80)   26068
weight                    101766     10          ?   98569
payer_code                101766     18          ?   40256
medical_specialty         101766     73          ?   49949
diag_1                    101766    717        428    6862
diag_2                    101766    749        276    6752
diag_3                    101766    790        250   11555
max_glu_serum             101766      4       None   96420
A1Cresult                 101766      4       None   84748
metformin                 101766      4         No   81778
repaglinide               101766      4         No  100227
nateglinide               101766      4         No  101063
chlorpropamide            101766      4         No  101680
glimepiride               101766      4         No   96575
acetohexamide             101766      2         No  101765
glipizide                 101766      4         No   89080
glyburide                 101766      4         No   91116
tolbutamide               101766      2         No  101743
pioglitazone              101766      4         No   94438
rosiglitazone             101766      4         No   95401
acarbose                  101766      4         No  101458
miglitol                  101766      4         No  101728
troglitazone              101766      2         No  101763
tolazamide                101766      3         No  101727
examide                   101766      1         No  101766
citoglipton               101766      1         No  101766
insulin                   101766      4         No   47383
glyburide-metformin       101766      4         No  101060
glipizide-metformin       101766      2         No  101753
glimepiride-pioglitazone  101766      2         No  101765
metformin-rosiglitazone   101766      2         No  101764
metformin-pioglitazone    101766      2         No  101765
change                    101766      2         No   54755
diabetesMed               101766      2        Yes   78363
readmitted                101766      3         NO   54864

In [24]:
def drop_columns_with_imbalance_distribution(categorical):
    a=categorical.describe(include=[np.object]).transpose()
    return categorical.drop(a[a['freq']>0.8*a['count']].transpose().columns,axis=1)

In [25]:
def drop_columns_with_null_distribution(categorical):
    a=categorical.describe(include=[np.object]).transpose()
        
        
    return categorical.drop(a[a['top']=='?'].transpose().columns,axis=1)


def drop_columns_with_high_levels(categorical):
    a=categorical.describe(include=[np.object]).transpose()
        
        
    return categorical.drop(a[a['unique']>100].transpose().columns,axis=1)

In [26]:
categorical1=drop_columns_with_imbalance_distribution(categorical).copy()

In [27]:
categorical2=drop_columns_with_null_distribution(categorical1)
categorical3=drop_columns_with_high_levels(categorical2)

In [ ]:
categorical3

In [28]:
# to handle gender column
def race_bin(x):
    if x=='Caucasian':
        return 1
    elif x=='AfricanAmerican':
        return 0
    else: return -1000

def gender_bin(x):
    if x=='Male':
        return 1
    elif x=='Female':
        return 0
    else:
        return -1000

def age_bin(x):
    if x=='[70-80)':
        return 80
    elif x=='[60-70)':
        return 70
    elif x=='[50-60)':
            return 60
    elif x=='[80-90)':
        return 90
    else:
        return -1000
    
def insulin(x):
    if x=='No':
        return 0
    elif x=='Steady':
        return 1
    elif x=='Yes':
        return 1
    
    else:return -1000

def change(x):
    if x=='No':
        return 0
    elif x=='Ch':
        return 1
    else: return -1000 





# to handle categorical columns with No, steady and yes

    



def readmitted_code(x):
    if x=='NO':
        return 0
    elif x=='>30':
        return 1
    elif x=='<30':
        return 1
    
    else:return -1000

def diabetesmed(x):
    if x=='No':
        return 0
    elif x=='Yes':
        return 1
    else: return -1000
# to handle Changed column

categorical4=pd.DataFrame()
categorical4['encounter_id']=categorical3['encounter_id']   
categorical4['age']=categorical3['age'].apply(lambda x: age_bin(x))
categorical4['gender']=categorical3['gender'].apply(lambda x: gender_bin(x))
categorical4['race']=categorical3['race'].apply(lambda x: race_bin(x))
categorical4['insulin']=categorical3['insulin'].apply(lambda x: insulin(x))
categorical4['diabetesMed']=categorical3['diabetesMed'].apply(lambda x: diabetesmed(x))
categorical4['change']=categorical3['change'].apply(lambda x: change(x))
categorical4['readmitted']=categorical3['readmitted'].apply(lambda x: readmitted_code(x))




In [29]:
categorical4

encounter_id   age  gender  race  insulin  diabetesMed  change  \
0            2278392 -1000       0     1        0            0       0   
1             149190 -1000       0     1    -1000            1       1   
2              64410 -1000       0     0        0            1       0   
3             500364 -1000       1     1    -1000            1       1   
4              16680 -1000       1     1        1            1       1   
...              ...   ...     ...   ...      ...          ...     ...   
101761     443847548    80       1     0    -1000            1       1   
101762     443847782    90       0     0        1            1       0   
101763     443854148    80       1     1    -1000            1       1   
101764     443857166    90       0     1    -1000            1       1   
101765     443867222    80       1     1        0            0       0   

        readmitted  
0                0  
1                1  
2                0  
3                0  
4                0  
...            ...  
101761           1  
101762           0  
101763           0  
101764           0  
101765           0  

[101766 rows x 8 columns]

In [30]:
y=categorical4['readmitted']
categorical_subset_edit_final=categorical4.drop(['readmitted'],axis=1)
dumm=categorical_subset_edit_final.drop('encounter_id',axis=1)
dumm=dumm.apply(lambda x: x.astype('category'),axis=0)
dumm=pd.get_dummies(dumm,drop_first=True)
dumm.apply(lambda x: x.astype('category'),axis=1)
#to remove dummy trap (multi collinearity caused due to dummy variable)
#dumm=dumm.drop(['age_70','gender_1','race_1','insulin_1','diabetesMed_0','change_0'],axis=1)

age_60  age_70  age_80  age_90  gender_0  gender_1  race_0  race_1  \
0            0       0       0       0         1         0       0       1   
1            0       0       0       0         1         0       0       1   
2            0       0       0       0         1         0       1       0   
3            0       0       0       0         0         1       0       1   
4            0       0       0       0         0         1       0       1   
...        ...     ...     ...     ...       ...       ...     ...     ...   
101761       0       0       1       0         0         1       1       0   
101762       0       0       0       1         1         0       1       0   
101763       0       0       1       0         0         1       0       1   
101764       0       0       0       1         1         0       0       1   
101765       0       0       1       0         0         1       0       1   

        insulin_0  insulin_1  diabetesMed_1  change_1  
0               1          0              0         0  
1               0          0              1         1  
2               1          0              1         0  
3               0          0              1         1  
4               0          1              1         1  
...           ...        ...            ...       ...  
101761          0          0              1         1  
101762          0          1              1         0  
101763          0          0              1         1  
101764          0          0              1         1  
101765          1          0              0         0  

[101766 rows x 12 columns]

In [31]:
dumm['encounter_id']=categorical4['encounter_id']


In [32]:
dumm

age_60  age_70  age_80  age_90  gender_0  gender_1  race_0  race_1  \
0            0       0       0       0         1         0       0       1   
1            0       0       0       0         1         0       0       1   
2            0       0       0       0         1         0       1       0   
3            0       0       0       0         0         1       0       1   
4            0       0       0       0         0         1       0       1   
...        ...     ...     ...     ...       ...       ...     ...     ...   
101761       0       0       1       0         0         1       1       0   
101762       0       0       0       1         1         0       1       0   
101763       0       0       1       0         0         1       0       1   
101764       0       0       0       1         1         0       0       1   
101765       0       0       1       0         0         1       0       1   

        insulin_0  insulin_1  diabetesMed_1  change_1  encounter_id  
0               1          0              0         0       2278392  
1               0          0              1         1        149190  
2               1          0              1         0         64410  
3               0          0              1         1        500364  
4               0          1              1         1         16680  
...           ...        ...            ...       ...           ...  
101761          0          0              1         1     443847548  
101762          0          1              1         0     443847782  
101763          0          0              1         1     443854148  
101764          0          0              1         1     443857166  
101765          1          0              0         0     443867222  

[101766 rows x 13 columns]

In [34]:
import numpy as np
from sklearn.preprocessing import StandardScaler
#scaling the numeric columns
a=StandardScaler()

numeric2.loc[:, numeric2.columns != 'encounter_id']=a.fit_transform(numeric2.loc[:, numeric2.columns != 'encounter_id'])
numeric2['encounter_id']=dumm['encounter_id']

In [35]:
import pandas as pd
# merging numeric and categorical columns

cleaned_df=dumm.merge(numeric2, how='inner',on=dumm['encounter_id'])

In [ ]:
#

'''
time_in_hospital correlated with num_medications,num_lab_procedures,num_diagnoses
num_procedures,num_medications are correlated
num_medications,num_procedurs are correlated
num_inpatient correlated with 


'''


In [36]:
#dropping encounter id of x and y dataframes
cleaned_df=cleaned_df.drop(['encounter_id_y','encounter_id_x'],axis=1)

In [37]:
#cleaned_df.shape
a=pd.DataFrame()
b=pd.DataFrame()
#a['cleaned_df']=
a['cleaned_df']=cleaned_df.columns
b['df']=df1.columns
#a['df']
a.to_csv('columns_list.csv')
b.to_csv('b.csv')
#a['cleaned_df']

In [39]:
cleaned_df_final=cleaned_df.rename(index=str,columns={'key_0':'encounter_id'})

In [ ]:
#cleaned_df_final=cleaned_df_final.drop(['age_-1000','gender_-1000','race_-1000','insulin_-1000','diabetesMed_0','change_0'],axis=1)

In [40]:
cleaned_df_final.columns

Index(['encounter_id', 'age_60', 'age_70', 'age_80', 'age_90', 'gender_0',
       'gender_1', 'race_0', 'race_1', 'insulin_0', 'insulin_1',
       'diabetesMed_1', 'change_1', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses'],
      dtype='object')

In [41]:
cleaned_df_final=cleaned_df_final[['age_60', 'age_70', 'age_80', 'age_90', 'gender_0',
       'gender_1', 'race_0', 'race_1', 'insulin_0', 'insulin_1',
       'diabetesMed_1', 'change_1', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses']]

In [42]:
#randomforest, decision tree, logistic, naive babe’s
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score,recall_score,precision_score,roc_curve

In [43]:
train,validate,y_train,y_validate=train_test_split(cleaned_df_final,y,train_size=0.7,shuffle=True)

In [44]:
validate

age_60  age_70  age_80  age_90  gender_0  gender_1  race_0  race_1  \
12529       0       1       0       0         1         0       0       1   
18433       0       0       0       0         1         0       0       1   
59781       0       0       1       0         0         1       0       1   
87913       1       0       0       0         1         0       0       1   
96566       0       1       0       0         1         0       0       1   
...       ...     ...     ...     ...       ...       ...     ...     ...   
77016       0       0       1       0         0         1       0       1   
98703       0       1       0       0         1         0       0       1   
24740       0       1       0       0         1         0       1       0   
7535        0       0       0       0         1         0       1       0   
18603       0       0       1       0         0         1       0       1   

       insulin_0  insulin_1  diabetesMed_1  change_1  time_in_hospital  \
12529          1          0              0         0         -1.137649   
18433          1          0              0         0          2.212331   
59781          1          0              1         1         -0.467653   
87913          0          0              1         1          0.202343   
96566          1          0              0         0         -1.137649   
...          ...        ...            ...       ...               ...   
77016          1          0              1         1         -0.132655   
98703          0          1              1         1          1.207337   
24740          1          0              1         1         -0.132655   
7535           1          0              1         1          0.202343   
18603          0          1              1         0         -0.802651   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
12529           -0.411484       -0.785398        -0.740920          -0.291461   
18433            0.960867        0.973309         0.489467          -0.291461   
59781           -0.462312       -0.785398        -0.125726          -0.291461   
87913            1.011695       -0.785398         1.842892          -0.291461   
96566           -1.021418       -0.785398         0.243390           2.864958   
...                   ...             ...              ...                ...   
77016           -0.360656       -0.785398         0.735544          -0.291461   
98703            0.554245       -0.199162         1.596815          -0.291461   
24740           -0.360656        0.387074         0.735544          -0.291461   
7535            -0.563967       -0.199162         0.120351          -0.291461   
18603            0.655900       -0.785398        -0.986997          -0.291461   

       number_emergency  number_inpatient  number_diagnoses  
12529         -0.212620          0.288579          0.298612  
18433         -0.212620         -0.503276         -0.735733  
59781         -0.212620          1.080434         -1.252906  
87913          0.862108          5.039710          0.815784  
96566          4.086293          1.080434          0.815784  
...                 ...               ...               ...  
77016         -0.212620         -0.503276          0.815784  
98703         -0.212620          0.288579          0.815784  
24740         -0.212620         -0.503276         -1.252906  
7535          -0.212620         -0.503276          0.298612  
18603         -0.212620         -0.503276          0.815784  

[30530 rows x 20 columns]

In [ ]:
len(train.columns)

In [45]:
#Global Model Building
model=GaussianNB()
model.fit(train,y_train)
predictions=model.predict(validate)
confusion_matrix(predictions,y_validate)
#roc_curve(y_validate, predictions, pos_label=2)

array([[14669, 10628],
       [ 1743,  3490]])

In [46]:
lg=LogisticRegression(C=0.1,penalty='l2',solver='newton-cg')
deci=DecisionTreeClassifier(max_depth=6,min_samples_split=0.5,min_samples_leaf=1,max_features=0.6)
#rf=RandomForestClassifier(bootstrap,)
nb=GaussianNB()

In [47]:
#Logistic Regression
log_metrics=pd.DataFrame()
log_results=pd.DataFrame()
c_array=[]
confusion=[]
solver_array=[]
log_results['y_validate']=y_validate
c_list=np.arange(0.1,0.7,0.1)
solver_list=['newton-cg']
log_results['y_validate']=y_validate
penalty='l2'
for solver in solver_list:
    for c in c_list:
        lg=LogisticRegression(C=c,penalty=penalty,solver=solver,verbose=True,n_jobs=5)
        model=lg.fit(train,y_train)
        log_results['predictions']=model.predict(validate)
        c_array.append(c)
        solver_array.append(solver)
        confusion.append(confusion_matrix(log_results['predictions'],y_validate))
#log_results['c']=c_array
#log_results['solver']=solver_array
log_metrics['confusion']=confusion

[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    3.1s finished
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    1.7s finished
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    2.3s finished
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    1.9s finished
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    2.0s finished
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    1.8s finished


In [48]:
log_metrics['confusion']

0    [[13224, 8497], [3188, 5621]]
1    [[13225, 8497], [3187, 5621]]
2    [[13224, 8499], [3188, 5619]]
3    [[13224, 8499], [3188, 5619]]
4    [[13224, 8499], [3188, 5619]]
5    [[13225, 8497], [3187, 5621]]
Name: confusion, dtype: object

In [49]:

lg=LogisticRegression(C=c,penalty=penalty,verbose=True,solver='newton-cg')
lg.fit(train,y_train)
predictions=lg.predict(validate)
confusion_matrix(predictions,y_validate)
#accuracy 62 %

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.9s finished


array([[13225,  8497],
       [ 3187,  5621]])

In [50]:
# Naive Baye's
model1=nb.fit(train,y_train)
predictions_nb=model1.predict(validate)

confusion_matrix(predictions_nb,y_validate)

array([[14669, 10628],
       [ 1743,  3490]])

In [ ]:
# Random Forest
'''
rf_results=pd.DataFrame()
results=[]
rf_metrics=pd.DataFrame()
max_leaf_nodes_array=[]
confusion=[]
min_impurity_decrease_array=[]
rf_results['y_validate']=y_validate
max_depth_list=np.arange(3,6,1)
max_leaf_nodes_list=np.arange(2,7,1)

min_impurity_decrease_list=[0.01,0.05,0.1]
oob_score=True
min_fraction_leaf_list=np.arange(0.4,0.8,0.1)
for max_depth in max_depth_list:
    for max_leaf_nodes in max_leaf_nodes_list:
        for min_impurity_decrease in min_impurity_decrease_list:
            rf=RandomForestClassifier(n_estimators=150,bootstrap=True,max_features='auto',max_leaf_nodes=max_leaf_nodes,min_impurity_decrease=min_impurity_decrease,min_samples_split=3,oob_score=True)
            model=rf.fit(train,y_train)
            results.append(model.predict(validate))
            max_leaf_nodes_array.append(max_leaf_nodes)
            min_impurity_decrease_array.append(min_impurity_decrease)
        
        confusion.append(confusion_matrix(predictions,y_validate))
rf_metrics['min_impurity_decrease_array']=min_impurity_decrease_array
rf_metrics['max_leaf_nodes_array']=max_leaf_nodes_array
#
'''

In [51]:

rf=RandomForestClassifier(oob_score=True,verbose=True,n_jobs=1,n_estimators=150)
rf.fit(train,y_train)
predictions_rf=rf.predict(validate)
confusion_matrix(predictions_rf,y_validate)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:   19.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:    1.7s finished


array([[11078,  6921],
       [ 5334,  7197]])

In [52]:
from keras.models import Sequential
from keras.layers import Dense,Conv1D,Flatten,Conv2D,MaxPooling1D,BatchNormalization,Dropout
from keras.optimizers import Adam
opt = Adam(lr=0.1)

from keras.callbacks import ReduceLROnPlateau, EarlyStopping


Using TensorFlow backend.


In [53]:
lrr = ReduceLROnPlateau(monitor='loss', min_delta=1e-4, factor=0.02,  patience=10)
early_stop = EarlyStopping(monitor='loss', min_delta=1e-2, patience=10, verbose=1)
error=[]
model=Sequential()
model.add(Dense(50,input_dim=20,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='softmax'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(train,y_train,epochs=100,callbacks=[early_stop],verbose=0)
#a=model.evaluate(validate,y_validate)

Epoch 00011: early stopping


In [54]:
predictions=model.predict(validate)
confusion_matrix(predictions,y_validate)

array([[    0,     0],
       [16412, 14118]])

In [ ]:
train.shape

In [ ]:
#train = np.expand_dims(train, axis=2)

In [55]:
train.shape[0]
nrows,ncols=train.shape
train_cnn=np.array(train).reshape(nrows, ncols, 1)

In [ ]:
train_cnn.shape

In [56]:
# Reshape the training set in the form of (nrows,ncols,1) and input shape=(ncols,1)

model=Sequential([
    Conv1D(16,kernel_size=1,activation='relu',input_shape=(20,1),),
MaxPooling1D(2),
Dropout(0.5),
BatchNormalization(),


Flatten(),
Dense(10,activation='relu'),
Dense(1,activation='softmax')])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(train_cnn,y_train,epochs=10,callbacks=[early_stop],verbose=1)

Epoch 1/10
71236/71236 [==============================] - 7s 93us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 2/10
71236/71236 [==============================] - 6s 85us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 3/10
71236/71236 [==============================] - 5s 75us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 4/10
71236/71236 [==============================] - 5s 75us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 5/10
71236/71236 [==============================] - 5s 74us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 6/10
71236/71236 [==============================] - 5s 74us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 7/10
71236/71236 [==============================] - 5s 73us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 8/10
71236/71236 [==============================] - 5s 73us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 9/10
71236/71236 [==============================] - 5s 73us/step - loss: 8.2766 - accuracy: 0.4602
Epoch 10/10
71236/71236 [==============================

In [57]:
nrows,ncols=validate.shape
validate_cnn=np.array(validate).reshape(nrows, ncols, 1)
predictions=model.predict(validate_cnn)
confusion_matrix(predictions,y_validate)

array([[    0,     0],
       [16412, 14118]])

In [58]:
validate_cnn

array([[[ 0.        ],
        [ 1.        ],
        [ 0.        ],
        ...,
        [-0.21262018],
        [ 0.28857905],
        [ 0.29861193]],

       [[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        ...,
        [-0.21262018],
        [-0.50327619],
        [-0.73573316]],

       [[ 0.        ],
        [ 0.        ],
        [ 1.        ],
        ...,
        [-0.21262018],
        [ 1.08043429],
        [-1.25290571]],

       ...,

       [[ 0.        ],
        [ 1.        ],
        [ 0.        ],
        ...,
        [-0.21262018],
        [-0.50327619],
        [-1.25290571]],

       [[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        ...,
        [-0.21262018],
        [-0.50327619],
        [ 0.29861193]],

       [[ 0.        ],
        [ 0.        ],
        [ 1.        ],
        ...,
        [-0.21262018],
        [-0.50327619],
        [ 0.81578448]]])

In [ ]:
#a=np.array(train).reshape((-1,22,1))
#b=np.array(y_train).reshape((-1,1))

In [59]:
import xgboost as xgb

In [ ]:
train.shape

In [60]:
params = {'eta': 0.02, 'max_depth': 5, 'subsample': 0.7, 'colsample_bytree': 0.7, 'objective': 'binary:logistic', 'seed': 99, 'silent': 1, 'eval_metric':'auc', 'nthread':4}

xg_train = xgb.DMatrix(train, label=y_train)
n_folds = 5
early_stopping = 10
cv = xgb.cv(params, xg_train, 5000, nfold=n_folds, early_stopping_rounds=early_stopping, verbose_eval=0)
model=xgb.train(params,xg_train)

In [ ]:
validate

In [61]:
#Xgboost
xg_val=xgb.DMatrix(validate)
predictions=model.predict(xg_val)
def predict_0_or_1(x):
    if x<0.64:
        return 0
    else: return 1
predictions=pd.Series(predictions).apply(lambda x:predict_0_or_1(x))

In [62]:
confusion_matrix(predictions,y_validate)

array([[16412, 14118],
       [    0,     0]])

In [63]:
from sklearn import tree
from sklearn.metrics import confusion_matrix

In [64]:
#Decision Tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train, y_train)
predictions=clf.predict(validate)
confusion_matrix(predictions,y_validate)

array([[9417, 6860],
       [6995, 7258]])

In [ ]:
train_y.shape

In [ ]:
vddfdffdfdddfv